---
title: "Discussion 11"
author: "Teryl Schmidt"
date: "11/28/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reading levels vary between different magazines. To avoid difficulties caused by different typefaces and sizes,
an investigator just counted the number of letters and punctuation signs. Random samples of 20 sentences
were selected from The New Yorker, Sports Illustrated, and National Geographic and the number of letters
and punctuation signs in each were tabulated. The resulting summary statistics are: </br>

<pre>
  New Yorker Sports   |  Illustrated National  |   Geographic
    y¯1 = 94.4        |        y¯2 = 92.9      |    y¯3 = 75.5
    s1 = 58.4         |        s2 = 54.2       |    s3 = 38.1
    n1 = 20           |        n2 = 20         |    n3 = 20
</pre>
Note: s<sup>2</sup><sub>i</sub> = ∑((y<sub>ij</sub>−y¯<sub>i</sub>)<sup>2</sup>  /  n<sub>i</sub> - 1) <br/>

1. In order to perform an ANOVA F test, what assumptions must be reasonably met? Check any of these
assumptions you can. <br/>

<font color="red">
The data are independent within and between treatments: </br>
Here groups are independent (ind. Between treatments)<br/>
The sentences are independent (ind. Within treatments)<br/>

The variances are the same for all treatments: </br>
if SD is between 0.5 - 2 <br/>
58.4 / 38.1 = 1.533 </br>
So can assume equal variance </br>

Each treatment has a normal distribution: </br>
Dont have original data so cant check. if had data could check QQ plot.
</font>

2. Construct the ANOVA table for this data and perform the relevant F test (assume that the necessary
assumptions are reasonably met.) <br/>
<pre>
Source          |  SS   | df                        | MS                                  | F
Treat (between) | SSTrt | df<sub>Trt</sub> = t - 1  | MS<sub>Trt</sub> / df<sub>Trt</sub> | F = MST<sub>Trt</sub> / MSE 
Error (Within)  | SSE   | df<sub>E</sub> = N - t    | MSE = SSE / df<sub>E</sub>          |
Total           | SSTot | df<sub>Tot>/sub> = N - 1  |                                     |


Source          |  SS       | df                      | MS                        | F                         | P
Treat (between) | 4414.8    | (t - 1) = (3 - 1) = 2   | 4414.8 / 2  = 2207.4      | 2207.4 / 2599.937 = 0.849 | 
Error (Within)  | 148196.4  | (N - t) = (60 - 3) = 57 | 148196.4 / 57 = 2599.937  |                           |
Total           | 152611.2  | (N - 1) = (60 - 1) = 59 |                           |                           |

P(F<sub>(2, 57)</sub> > 0.8497)

P(F<sub>(2.57 > 0.8497)</sub>)
57 = between 50 - 60
First column?
0.8 > 0.100
0.100
P > 0.100
0.433

</pre>
Can do this for this because all groups have same sample size (Do Not Use This)
y¯ = 94.4 + 92.9 + 75.5 / 3 = 212.4667

If not same sample size between groups use: (Use This)
(y1 * n1) + (y2 * n2) + (y3 * n3) / (n1 + n2 + n3)
((94.4 * 20) + (92.9 * 20) + (75.5 * 20)) / (20 + 20 + 20) = 87.6

(20 * (94.4 - 87.6)^2) + (20 * (92.9 - 87.6)^2) + (20 * (75.5 - 87.6)^2) = 4414.8

19 * 58.4^2 + 19 * 54.2^2 + 19 * 38.1^2 = 148196.4

SSTrt + SSE = 4414.8 + 148196.4 = 152611.2





