---
title: "Lecture14ANOVA"
author: "Chelsey Green"
date: "7/24/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Plant1<-c(438, 619, 732, 638)
Plant2<-c(857, 1014, 1153, 883, 1053)
Plant3<-c(925, 786, 1179, 786)
Plant4<-c(893, 891, 917, 695, 675, 595)

Plantdata<-data.frame(Plant=c(rep("Plant1",4), rep("Plant2", 5), rep("Plant3", 4), rep("Plant4",6)), Data=c(Plant1, Plant2, Plant3, Plant4), gpmeans=c(rep(606.8, 4),rep(992.0, 5), rep(919.0, 4), rep(777.7, 6)))

require(plyr)
group.mu <- ddply(Plantdata, "Plant", summarise, grp.mean=round(mean(Data), 1))
group.mu

mean(Plant1); length(Plant1); sd(Plant1)
mean(Plant2); length(Plant2); sd(Plant2)
mean(Plant3); length(Plant3); sd(Plant3)
mean(Plant4); length(Plant4); sd(Plant4)
mean(Plantdata$Data); length(Plantdata$Data); sd(Plantdata$Data)

require(ggplot2)

ggplot(data=Plantdata, aes(x=Plant, y=Data, color=Plant))+
  geom_jitter(width=0.1)+
  theme_bw()
  #geom_errorbar(aes(ymax=gpmeans, ymin=gpmeans))+
  #geom_hline(yintercept=827.8421)

ggplot(data=Plantdata, aes(x=Plant, y=Data, color=Plant))+
  geom_jitter(width=0.1)+
  theme_bw()+
  geom_errorbar(aes(ymax=gpmeans, ymin=gpmeans))+
  geom_hline(yintercept=827.8421)

data.tight<-data.frame(Group=c(rep("Treat1", 4), rep("Treat2", 4), rep("Treat3", 4)), ObservedVals=c(2, 2.5, 3.5,4, 6, 6.5, 7.5, 8, 3, 3.5, 4.5, 5))

data.wide<-data.frame(Group=c(rep("Treat1", 4), rep("Treat2", 4), rep("Treat3", 4)), ObservedVals=c(0,2,4,6,4,6,8,10,1,3,5,7))

ggplot(data=data.tight, aes(x=Group, y=ObservedVals, color=Group))+
  geom_jitter(width=0.1)+
  theme_bw()+
  ylim(-1,11)

ggplot(data=data.wide, aes(x=Group, y=ObservedVals, color=Group))+
  geom_jitter(width=0.1)+
  theme_bw()+
  ylim(-1,11)


```
\begin{tabular}{rrrrrr|lll}
  \multicolumn{6}{l}{Plant 1} & $n_i$ & $\bar{y}_{i.}$ & $s_i$\\
  438 & 619 & 732 & 638 &    &    &    4 & 606.8  & 122.9 \\
 \hline
  \multicolumn{6}{l}{Plant 2}\\
  857 & 1014 & 1153 & 883 & 1053   &   & 5 & 992.0 & 122.7\\
\hline
  \multicolumn{6}{l}{Plant 3}\\
  925 & 786 & 1179 & 786     & &   & 4 & 919.0 & 185.3\\
\hline
 \multicolumn{6}{l}{Plant 4}\\
  893 & 891 & 917 & 695 & 675 & 595      & 6 & 777.7 & 138.8\\
\hline
  \multicolumn{9}{r}{Overall: $N = 19, \bar{y}_{..} = 827.8$}\\
\end{tabular}

```{r}
Plantdata$OverallMean<-827.8
Plantdata$Treateff<-(Plantdata$gpmeans-Plantdata$OverallMean)
Plantdata$Resid<-(Plantdata$Data-Plantdata$gpmeans)
Plantdata$Obs_Overall<-Plantdata$Data-827.8

A.SSTot<-sum((Plantdata$Obs_Overall)^2)
A.SSTreat<-sum((Plantdata$Treateff^2))
A.SSError<-sum((Plantdata$Resid^2))

Plantdata$OverallMeanT<-mean(Plantdata$Data)
Plantdata$gpmeansT<-c(rep(mean(Plant1), length(Plant1)),rep(mean(Plant2), length(Plant2)), rep(mean(Plant3), length(Plant3)), rep(mean(Plant4), length(Plant4))) 
Plantdata$TreateffT<-(Plantdata$gpmeansT-Plantdata$OverallMeanT)
Plantdata$ResidT<-(Plantdata$Data-Plantdata$gpmeansT)
Plantdata$Obs_OverallT<-Plantdata$Data-mean(Plantdata$Data)

SSTot<-sum((Plantdata$Obs_OverallT)^2)
SSTreat<-sum((Plantdata$TreateffT^2))
SSError<-sum((Plantdata$ResidT^2))

ggplot(data=Plantdata, aes(x=Plant, y=Data, color=Plant))+
  geom_jitter(width=0.1)+
  theme_bw()+
  geom_errorbar(aes(ymax=gpmeans, ymin=gpmeans))+
  geom_hline(yintercept=827.8421)+
  #geom_segment(aes(x=Plant,y=827.8421, yend=gpmeans, xend=Plant))
  #geom_segment(aes(ymin=gpmeans, ymax=Data))+
  geom_errorbar(aes(ymin=Data, ymax=827.8421))
```
Observations: $y_{ij}$

$$\left[\begin{array}
{rrrrrr}
438 & 619 & 732 & 638 \\
857 & 1014 & 1153 & 883 & 1053 \\
925 & 786 & 1179 & 786 \\
893 & 891 & 917 & 695 & 675 & 595
\end{array}\right]
$$

$$\left[\begin{array}
{rrrrrr}
827.8 & 827.8 & 827.8 & 827.8 \\
827.8 & 827.8 & 827.8 & 827.8 & 827.8 \\
827.8 & 827.8 & 827.8 & 827.8 \\
827.8 & 827.8 & 827.8& 827.8 & 827.8 & 827.8
\end{array}\right]
$$

$$\left[\begin{array}
{rrrrrr}
-221 & -221  & -221  & -221  \\
164.2 & 164.2 & 164.2 & 164.2 & 164.2 \\
91.2 & 91.2 & 91.2 & 91.2 \\
-50.1 & -50.1 & -50.1& -50.1 & -50.1 & -50.1
\end{array}\right]
$$

$$\left[\begin{array}
{rrrrrr}
-168.8 & 12.2  & 125.2  & 31.2  \\
-135 & 22 & 161 & -109 & 61 \\
6 & -133 & 260 & -133 \\
115.3 & 113.3 & 139.3& -82.7 & -102.7 & -182.7
\end{array}\right]
$$

$$\left[\begin{array}
{rrrrrr}
-389.8 & -208.8  & -95.8  & -189.8  \\
29.2 & 186.2 & 325.2 & 55.2 & 225.2 \\
97.2 & -41.8 & 351.2 & -41.8 \\
65.2 & 63.2 & 89.2 & -132.8 & -152.8 & -232.8
\end{array}\right]
$$

Doing the ANOVA in R
```{r}
Plantanova<-aov(Data~Plant, data=Plantdata)
summary(Plantanova)
hist(Plantanova$residuals)
qqnorm(Plantanova$residuals)

Plantlm<-lm(Data~Plant, data=Plantdata)
anova(Plantlm)
plot(Plantlm)

ggplot(data=Plantdata, aes(x=Plant, y=(Data-gpmeans), col=Plant))+
    geom_point()
  
hist(Plantanova$residuals)

#Fisher LSD CIs:
ft<-qt(p=0.05/2, df=15, lower.tail=FALSE)
#Sample sizes of 4 and 5
(F4_5ME=ft*sqrt(20322.54*(1/4+1/5)))
(diff1_2<-606.8-992.0)
diff1_2+F4_5ME; diff1_2-F4_5ME

(diff2_3<-992-919)
diff2_3+F4_5ME; diff2_3-F4_5ME

#Sample sizes of 4 and 4
(F4_4ME=ft*sqrt(20322.54*(1/4+1/4)))
(diff1_3<-606.8-919.0)
diff1_3+F4_4ME; diff1_3-F4_4ME

#Sample sizes of 4 and 6
(F4_6ME=ft*sqrt(20322.54*(1/4+1/6)))
(diff1_4<-606.8-777.7)
diff1_4+F4_6ME; diff1_4-F4_6ME

(diff3_4<-919-777.7)
diff3_4+F4_6ME; diff3_4-F4_6ME

#Sample sizes of 5 and 6
(F5_6ME=ft*sqrt(20322.54*(1/5+1/6)))
(diff2_4<-992.0-777.7)
diff2_4+F5_6ME; diff2_4-F5_6ME

#Bonferroni Multiple Comparison Adjustment
qt(p=.0042, df=15, lower.tail=FALSE)

#Tukey Multiple Comparison Adjustment
TukeyHSD(Plantanova)
qtukey(p=(1-0.05), nmeans=4, df=(19-4)) / sqrt(2)

#Kruskal-Wallis Test
kruskal.test(Data~Plant, data=Plantdata)

#post-hoc Wilcoxon Rank Sum
wilcox.test(x=Plant1, y=Plant2, paired=FALSE)
wilcox.test(x=Plant1, y=Plant3, paired=FALSE)
wilcox.test(x=Plant1, y=Plant4, paired=FALSE)
wilcox.test(x=Plant2, y=Plant3, paired=FALSE)
wilcox.test(x=Plant2, y=Plant4, paired=FALSE)
wilcox.test(x=Plant3, y=Plant4, paired=FALSE)
```

